[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.9

[colors.primary]
background = "#272a32"
foreground = "#D8DADC"

[font]
normal.family = "FiraCode Nerd Font"
# normal.family = "Hack Nerd Font"
normal.style = "Bold"
size = 10.0

[cursor]
unfocused_hollow = false
blink_interval = 500

[cursor.style]
blinking = "Always"
shape = "Block"